spring.application.name=server

spring.datasource.url=jdbc:mariadb://berell-piserver.duckdns.org:3306/berell
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080
