spring.application.name=server

spring.datasource.url=jdbc:mariadb://localhost:3307/berell
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Disabling Spring Securitys default auto-configuration as we only use the crypto part of it
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server.port=8080
server.address=0.0.0.0

# Looked into different ways of storing the key but everything included a coded String containing a secret or a password.
# So this is not the best way to hide the secret but the only way i could find that seems plausible in this kind of project
jwt.secretKey=RmV2dDJDZzJ5MkVma1B4R3lNdE1qYzBHRnBzYklBUTA=